version: '3.8'

services:
  glm-ocr-server:
    image: vllm/vllm-openai:v0.19.0-ubuntu2404
    container_name: ocr_glm
    ports:
      - "8080:8080"
    command: ["--model", "zai-org/GLM-OCR", "--port", "8080", "--speculative-config", "{\"method\": \"mtp\", \"num_speculative_tokens\": 3}", "--served-model-name", "glm-ocr"]
    volumes:
      - glm_data:/root/.cache/huggingface

  ocr-cannabis:
    build: .
    container_name: ocr_prescrizioni
    ports:
      - "8501:8501"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    depends_on:
      - glm-ocr-server

volumes:
  glm_data:
