version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ocr_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ocr-cannabis:
    build: .
    container_name: ocr_prescrizioni
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./input:/app/input
      - ./output:/app/output
    depends_on:
      - ollama
    network_mode: host

volumes:
  ollama_data:
